version: "3"

services:
    mysql:
        build: ./dockerfiles/mysql
        ports:
            - "33075:3306"
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: 123456789
            MYSQL_DATABASE: gravity_falls
    app:
        build: .
        depends_on:
            - mysql
        links:
            - mysql
        ports:
            - 22513:3000
volumes:
    mysql-data:
        driver: "local"